### ISSUE TITLE
Safe for user input?

### ISSUE THREAD

**Issue by tjconcept** [dominictarr/parse-regexp#3]
Would it be safe to parse user input using this module and feed it to i.e. a MongoDB query?

**Comment by dominictarr** [comment]
almost. I suggest you pass it though https://github.com/substack/safe-regex first,
as there exist some exponential time regular expressions that will effectively block your CPU,
there are actually old versions of mongo that where succeptable to this, but it had already been fixed by the time I learned about exponential time regexps.

**Comment by tjconcept** [comment]
Ah, interesting, I didn't knew about that. Thanks.
